name: Running update...

on:
  push:
    branches: [main]
  schedule:
    - cron: "*/59 * * * *"  # Задава на всеки половин час
  workflow_dispatch:

permissions:
  contents: write  # Позволява писане на съдържание (за commit и push)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config --global user.name "belchew"
          git config --global user.email "belchew@outlook.com"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip freeze  # За диагностика
      - name: Install Playwright
        run: |
          python -m pip install playwright
          python -m playwright install

      - name: Verify pandas installation
        run: |
          python -c "import pandas; print(pandas.__version__)"

      - name: Run your script
        run: |
          python scrape.py

      - name: Commit and push updated sources.m3u
        run: |
          git add sources.m3u
          git commit -m "Update sources.m3u via GitHub Actions" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
