name: Daily Scraper

on:
  schedule:
    - cron: "0 6 * * *"  # Всеки ден в 06:00 UTC
  workflow_dispatch:  # Позволява ръчно стартиране

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper script
        run: python passgen.py  # Изпълнява скрипта

      - name: Set Git user info
        run: |
          git config --global user.name "belchew"  # Твоето потребителско име в GitHub
          git config --global user.email "belchew@outlook.com"  # Твоят имейл в GitHub

      - name: Commit and push key.txt to repository
        run: |
          git add key.txt
          git commit -m "Update key.txt with new data"
          git push https://x-access-token:${{ secrets.NEW_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
