name: refreshing...

on:
  push:
    branches: [main]
  schedule:
    - cron: "01 */1 * * *"  # 
  workflow_dispatch:

permissions:
  contents: write  # Позволява push към репото

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repo (connectdirect)
        uses: actions/checkout@v3
        with:
          persist-credentials: false  #  Ще използваме PAT вместо default GITHUB_TOKEN

      - name: Checkout private repo (connecting)
        uses: actions/checkout@v3
        with:
          repository: belchew/connecting
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: connecting
          persist-credentials: false

      - name: Copy sources.m3u from private repo
        run: |
          cp connecting/sources.m3u ./

      - name: Push using PAT
        env:
          GH_PAT: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          git config user.name "belchew"
          git config user.email "belchew@outlook.com"
          git rm -r --cached connecting || true  # Премахва embedded git
          git add sources.m3u
          git commit -m "ReNewed orgin strings" || echo "Nothing to commit"
          git remote set-url origin https://belchew:${GH_PAT}@github.com/belchew/connectdirect.git
          git push origin HEAD
