name: auto-refresh

on:
  push:
    branches: [main]
  schedule:
    - cron: '01 */1 * * *'  # веднъж на час
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          repository: belchew/connecting
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: connecting

      - name: Copy sources.m3u file
        run: |
          cp connecting/sources.m3u .
          echo "sources.m3u copied successfully"
