name: read-only-refresh

on:
  workflow_dispatch:

jobs:
  copy-only:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: belchew/connecting
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: connecting

      - name: Copy file
        run: cp connecting/sources.m3u .
      
